import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="site-header">
          <Image
            src="/logo_color.svg"
            alt="Logo Fakulty hospodárskej informatiky"
            width={40}
            height={40}
            priority
          />
          <div className="site-header__title">
            <span>Fakulta hospodárskej informatiky</span>
            <span className="site-header__subtitle">Ekonomická univerzita v Bratislave</span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
