import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="site-header">
          <Image
            src="https://ih1.redbubble.net/image.5522694112.0403/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8.u1.jpg"
            alt="Gym Bro Logo"
            width={50}
            height={50}
            priority
          />
          <div className="site-header__title">
            <span>Gym Bro</span>
            <span className="site-header__subtitle">Your AI Fitness Coach</span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
